---
- name: Spin up spot instances
  hosts: 127.0.0.1
  connection: local
  tasks:
    - name: create  {{ spot_count }} spot instances with spot_price of ${{ spot_price }}      
      local_action:
        module: ec2
        region: eu-west-1
        spot_price:  '{{ spot_price }}'
        spot_wait_timeout: 360
        keypair: wh-training
        instance_type: m3.xlarge
        image: ami-6e7bd919
        wait: yes
        instance_tags:
         foo: bar
        exact_count: '{{ spot_count }}'
        #group: test-group
        #count:  '{{ spot_count }}'
      register: ec2

#    - name: Tag instances
#      local_action: ec2_tag resource= region=eu-west-1 state=present
#      with_items: ec2.instances
#      args:
#        tags:
#          Spot: '{{ spot_price }}'
#
#
